name: CI/CD Pipeline

on:
  pull_request:
    branches: ["master"]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Source
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build Docker Image
        run: docker build -t pabasaraa/ctse-app .

      - name: Publish image to docker hub
        run: docker push pabasaraa/ctse-app:latest

      - name: Deploy to EC2 instance
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_PRIVATE_KEY}}
          script: |
            sudo apt-get update
            sudo apt-get install -y docker.io
            docker stop ctse-app || true
            docker rm ctse-app || true
            docker pull ${{ secrets.DOCKER_USERNAME }}/ctse-app:latest
            docker run -d --name ctse-app -p 5173:5173 ${{ secrets.DOCKER_USERNAME }}/ctse-app:latest
